// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// get an attribute on a file
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> get_attribute(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Char> attribute,
);

/// free a string
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void free_string(ffi.Pointer<ffi.Char> str);
